using System.Collections.Generic;

namespace GiffyCards.Common
{
    public class CigarSeedDataConstants
    {
        public static readonly string[] CigarNameList = { "BOLIVAR CORONAS JUNIOR", "BOLIVAR PETIT CORONAS", "BOLIVAR ROYAL CORONAS", "COHIBA 1966 EDICION LIMITADA 2011- NO DISCOUNTS APPLY", "COHIBA BEHIKE 52",
            "COHIBA BEHIKE 54", "COHIBA BEHIKE 56", "COHIBA ESPLENDIDOS", "COHIBA MADURO 5 GENIOS", "COHIBA MADURO 5 MAGICOS", "COHIBA ROBUSTO", "COHIBA MEDIO SIGLO",
            "COHIBA TALISMAN EDICION LIMITADA 2017", "COHIBA MAJESTUOSOS 1966", "COHIBA MEDIO SIGLO TUBOS", "COHIBA ROBUSTOS RESERVA COSECHA 2014", "COHIBA MEDIO SIGLO TUBOS",
            "CUABA SALOMONES", "CUABA BARIAY BOOK 2012 - NO DISCOUNTS APPLY", "DIPLOMATICOS NORTENOS 2018 CANADA REGIONAL EDITION", "EL-REY-DEL-MUNDO DEMI TASSE", "FONSECA NO. 1",
            "HOYO-DE-MONTERREY DOUBLE CORONAS", "HOYO-DE-MONTERREY EPICURE NO. 2 (OPEN BOX)", "HOYO-DE-MONTERREY EPICURE ESPECIAL", "HOYO-DE-MONTERREY PETIT ROBUSTO",
            "HOYO-DE-MONTERREY LE HOYO DE SAN JUAN", "HOYO-DE-MONTERREY EPICURE DE LUXE - LCDH", "HOYO-DE-MONTERREY EPICURE NO. 2 RESERVA COSECHA 2012", "HOYO-DE-MONTERREY PETIT BELICOSOS EDICION LIMITADA - 2017",
            "H.UPMANN NO. 2", "H.UPMANN MAGNUM 46", "H.UPMANN MAGNUM 50 TUBOS", "H.UPMANN MAGNUM 54", "H.UPMANN SIR WINSTON GRAN RESERVA COSECHA 2011", "H.UPMANN NO. 2 RESERVA COSECHA 2010 - NO DISCOUNTS APPLY",
            "H.UPMANN MAGNUM 50 TUBOS", "JOSE-L.-PIEDRA BREVAS", "JOSE-L.-PIEDRA CAZADORES", "JUAN-LOPEZ SELECCION NO. 2", "MONTECRISTO NO. 2", "MONTECRISTO NO. 3", "MONTECRISTO NO. 4",
            "MONTECRISTO NO. 5", "MONTECRISTO OPEN EAGLE", "MONTECRISTO OPEN JUNIOR", "MONTECRISTO OPEN MASTER", "MONTECRISTO OPEN MASTER TUBOS", "MONTECRISTO 80 ANIVERSARIO",
            "MONTECRISTO GRAN PIRAMIDES LIMITED EDITION 2017", "MONTECRISTO SUPREMOS EDICION LIMITADA 2019", "PARTAGAS ARISTOCRATS", "PARTAGAS PRESIDENTES", "PARTAGAS SERIES NO. 1 EDICION LIMITADA 2017",
            "PARTAGAS SERIE E NO. 2 TUBOS", "PUNCH PUNCH 48 - LCDH", "PUNCH SHORT DE PUNCH", "QUAI-DORSAY NO. 54", "QUINTERO-BREVAS", "DAVIDOFF LIMITED EDITION YEAR OF THE DOG 2018",
            "DAVIDOFF LIMITED EDITION YEAR OF THE ROOSTER 2017", "DAVIDOFF SIGNATURE NO.2 TUBOS", "DAVIDOFF MILLENNIUM BLEND ROBUSTO", "RAMON ALLONES SMALL CLUB CORONAS", "RAMON ALLONES SPECIALLY SELECTED",
            "ROMEO-Y-JULIETA BELICOSOS", "ROMEO-Y-JULIETA WIDE CHURCHILLS GRAN RESERVA COSECHA 2009", "ROMEO-Y-JULIETA CHURCHILLS RESERVA COSECHA 2008", "ROMEO-Y-JULIETA MARAVILLAS 8 (YEAR OF THE RAT 2020)",
            "SAN-CRISTOBAL JARRA TORREON - NO DISCOUNTS APPLY", "SAN-CRISTOBAL LA FUERZA", "TRINIDAD CASILDA COLECCION HABANOS 2019", "TRINIDAD MEDIA LUNA", "VEGAS-ROBAINA UNICOS", "VEGUEROS CENTROFINOS"
            , "VEGUEROS TAPADOS", "H.UPMANN NO. 2 RESERVA COSECHA 2010 - NO DISCOUNTS APPLY", "COHIBA SIGLO VI GRAN RESERVA 2003 - NO DISCOUNTS APPLY", "ROMEO-Y-JULIETA FABULOSOS NO. 2 - HABANOS COLECCIÓN 2016 BOOK",};

        public static readonly decimal[] UnitPrice = { 8.00m, 9.00m, 12.50m, 337.00m, 175.00m, 169.00m, 194.00m, 47.50m, 36.50m, 31.00m, 25.00m, 18.00m, 99.00m, 725.00m, 25.00m, 165.00m,
            25.50m, 24.50m, 87.50m, 28.00m,5.50m, 9.00m, 24.50m, 13.50m, 14.50m, 10.50m,18.00m, 17.00m, 82.00m, 37.00m,15.50m, 13.00m, 19.50m, 18.00m ,220.00m, 210.00m, 19.00m,
            5.00m,5.00m, 12.50m, 18.00m,12.50m, 9.50m,8.00m, 18.00m, 25.00m, 16.50m, 56.00m, 180.00m, 25.00m, 6.00m,16.00m, 45.00m, 26.00m, 27.50m, 29.50m,
            35.00m, 4.00m, 45.00m, 50.00m, 17.00m, 20.00m, 7.00m, 13.00m, 15.00m, 174.00m,220.00m, 82.00m, 60.00m, 13.00m, 188.00m, 21.00m, 18.00m, 25.00m, 10.00m, 221.00m, 254,00m, 245.00m,};

        public static readonly string[] LengthRangeList = { "4", "5", "4", "6", "4", "5", "6", "7", "5", "4", "4", "4", "6", "5", "4", "4", "4", "7", "9", "4", "4", "6", "7", "4",
            "5", "4", "5", "4","4","4", "6","5", "6", "4", "7", "6","6", "5","6","4","6","5","5","4","5", "4","4","6", "6", "5","5","6","5","5","5","4","5","5", "7","6","6",
            "5","4", "4","5","5","7","6","5","5","7", "4", "6","5","4","6","5","7", "5",};

        public static readonly string[] RingRangeList = { "42", "42", "50", "52", "52", "54", "56", "47", "52", "52", "50", "52", "54", "58", "52","50", "52", "57", "47", "50",
            "30", "44", "49", "50", "50", "50", "54", "52","52","52", "46", "50", "54", "47","52", "50", "42","43", "50", "52", "42", "42", "40","54", "38", "50",
            "34", "55", "57","55", "40", "47","52", "55", "49","55", "54", "40", "50","50", "38", "50", "42", "50", "52","55", "47","55","54","50","53","50","52","50", "46",
            "52","52","52","49",};

        public static readonly string[] ShapeList = { "Corona", "Petit Corona", "Robusto", "Double Robusto", "Petit Robusto", "Robusto Extra", "Double Robusto", "Churchill", "Robusto Extra",
            "Petit Robusto" , "Robusto", " Petit Robusto", "Robusto Extra",  "Robusto Extra", "Petit Robusto", "Robusto", "Petit Robusto", "Double Perfecto", "Corona"
           , "Robusto", "Small Panetela", "Lonsdale", "Double Corona", "Robusto", "Robusto Extra", "Petit Robusto", "Robusto Extra", "Petit Robusto", "Robusto", "Petit Pyramid",
            "Pyramid", "Corona Gorda", "Double Robusto", "Petit Robusto", "Churchill", "Pyramid", "Double Robusto", "Corona", "Long Corona", "Robusto", "Torpedo",
            "Corona", "Petit Corona", "Petit Corona", "Robusto Extra", "Short Panetela","Robusto", "Robusto", "Double Robusto", "Pyramid", "Robusto", "Petit Corona", "Perfecto",
            "Robusto Extra", "Robusto Extra", "Grand Corona", "Petit Robusto", "Edmundo Grueso", "Corona", "Churchill", "Diademas Finas", "Panetela", "Robusto", "Petit Corona",
            "Robusto","Belicoso", "Robusto", "Churchill", "Robusto Extra", "Robusto", "Robusto Extra", "Double Robusto", "Petit Robusto", "Torpedo", "Robusto", "Corona Extra",
            "Pyramid", "Robusto Extra","Robusto Extra",
        };

        public static readonly string[] TesteList = { "Earthy", "Earthy", "Spicy", "Spicy", "Woody", "Woody", "Woody", "Vegetal", "Woody", "Spicy", "Spicy", "Spicy", "Vegetal",
            "Spicy", "Spicy", "Spicy", "Woody", "Woody", "Woody", "Fruity", "Spicy", "Spicy", "Fruity", "Spicy", "Woody","Woody", "Spicy", "Fruity","Fruity",
            "Spicy","Spicy", "Woody","Woody", "Vegetal", "Spicy", "Woody", "Vegetal","Vegetal","Vegetal", "Spicy", "Woody", "Earthy","Vegetal", "Woody", "Woody",
            "Woody", "Woody", "Spicy","Spicy","Woody", "Leathery", "Earthy","Woody","Woody", "Leathery","Earthy", "Earthy", "Earthy", "Spicy","Spicy","Spicy","Woody",
            "Woody", "Spicy", "Vegetal", "Leathery","Leathery","Leathery","Earthy","Earthy", "Woody","Fruity","Earthy","Spicy","Vegetal","Vegetal","Spicy","Woody","Earthy",};

        public static readonly string[] StrenghtList = { "Full", "Medium to Full", "Medium to Full", "Medium to Full", "Medium to Full", "Medium to Full", "Full", "Medium to Full", "Medium to Full",
            "Medium to Full", "Medium to Full", "Medium", "Medium to Full", "Medium", "Medium to Full", "Medium", "Full", "Medium", "Medium to Full", "Light",
            "Light to Medium", "Light to Medium", "Light to Medium", "Medium to Full", "Light to Medium", "Light", "Light","Light to Medium","Light to Medium", "Medium",
            "Medium to Full", "Medium to Full", "Medium to Full", "Medium","Medium", "Medium to Full", "Medium to Full", "Medium", "Medium", "Medium to Ful", "Medium to Full",
            "Medium to Full", "Medium to Full", "Light to Medium", "Light to Medium", "Light to Medium", "Light to Medium", "Medium to Full","Medium to Full","Medium to Full",
            "Full",  "Full", "Medium to Full", "Medium to Full", "Medium","Light", "Light", "Light to Medium", "Medium","Medium", "Light to Medium", "Medium to Full",
            "Medium to Full", "Medium to Full","Medium to Full", "Medium","Medium","Medium","Medium", "Light to Medium","Light", "Medium", "Medium to Full", "Full","Full", "Medium",
            "Medium to Full", "Medium to Full","Medium to Full",
        };

        public static readonly string[] ImageUrl = { "https://cigarmalaysia.com/1626-large_default/bolivar-coronas-junior.jpg", "https://cigarmalaysia.com/1396-large_default/bolivar-petit-coronas.jpg",
        "https://cdn11.bigcommerce.com/s-7s4zj/images/stencil/1280x1280/products/18/317/Bolivar_royal_coronas_Tubos_x10_caja__51104.1420634869.jpg?c=2", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-1966-edicion-limitada-2011_2_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_11.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-behike-56_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_10.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-esplendidos-stick.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-siglo-i-stick_18.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-esplendidos-stick.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/g/e/genios-1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/a/magicos-1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba_robusto_2_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/e/medio-siglo-tuboc-1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-talisman-edicion-limitada-2017-1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-1966-0.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/e/medio-siglo-tuboc-1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-robustos-reserva-cosecha-2014-1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/e/medio-siglo-tuboc-1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-siglo-vi-gran-reserva_single.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/u/cuaba-bariay-book-2012_29_1_1_1_1_1_1_1_1_2_4_1_10.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/d/i/dip-canada-1_1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/e/l/el-rey-del-mundo-demi-tasse-1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/f/o/fonseca-delicias_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/o/hoyo-de-monterrey-double-coronas_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/o/hoyo-de-monterrey-epicure-no2_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/o/hoyo-de-monterrey-epicure-especial_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_7_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/o/hoyo-de-monterrey-petit-robusto_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/o/hoyo-de-monterrey-le-hoyo-de-san-juan-stick_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/o/hoyo-delux-box-stick_1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/e/p/epicure-no.2-gran-6.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/o/hoyo-2017-5.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/-/h-upmann-no-2_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/-/h-upmann-magnum-46_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/-/h-upmann-magnum-50_6_4_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/a/magnum54-stick_3.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/s/i/sir-winston-gr-7_1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/_/h.-upmann-no.-2-reserva--cosecha-2010-stick.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/-/h-upmann-magnum-50_6_4_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/j/o/jose-l-piedra-brevas_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/j/o/jose-l-piedra-cazadores_1_1_1_1_1_2_4_1_6_2.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/j/u/juan-lopez-seleccion-no2_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/montecristo-no.2-stick-new-band.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/montecrisot-3-stick.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/monte-no.-4.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/montecristo-no.5-stick.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/e/a/eagle_1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/montecristo-open-junior_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/montecristo-master-stick.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/a/master-tubos-stick.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/montecristo-80th-0.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/montecristo-gran-piramides-1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/m/o/montecristo-supremos-2019-1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/p/a/partagasa-ar1_2_1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/p/a/partagas-presidentes_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/p/a/partagas-series-no.1-1_1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/p/a/partagas-serie-e-no.2-tubos-single.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/p/u/punch-48-stick.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/p/u/punch-short-de-punch-1_1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/q/u/quai-d_orsay-no.-54-stick.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/j/o/jose-l-piedra-brevas_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/d/o/dog-2018-stick.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/d/a/davidoff2017-stick.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/d/a/davidoff-signature-no.2-tubos-stick.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/d/a/davidoff-millennium-blend-robusto_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/r/a/ramon-allones-small-club-corona_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/r/a/ramon-allones-specially-selected_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/r/o/romeo-y-julieta-belicosos_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/r/o/romeo-y-julieta-wide-churchills-gran-reserva-cosecha-2009_2.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/r/y/ryj-churchull-gran-reserva-2008-5.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/r/y/ryj-churchull-gran-reserva-2008-5.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/r/o/romeo-y-julieta-maravillas-8-single_1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/s/a/san-cristobal-jarra-torreon_6_2_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/s/a/san-cristobal-la-fuerza-1.jpg", "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/t/r/trinidad-casilda-coleccion-1.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/t/r/trinidad-coloniales_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg","https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/v/e/vegas-robaina-famosos_1_1_2_1_1_1_4_1_1_1_1_1_1_1_1_2_4_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/v/e/vegueros-centrofinos-3_2.jpg","https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/v/e/vegueros-tapados-stick_1_9.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/h/_/h.-upmann-no.-2-reserva--cosecha-2010-stick.jpg","https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/c/o/cohiba-siglo-vi-gran-reserva_single.jpg",
        "https://www.finestcubancigars.com/media/catalog/product/cache/3d77c04fa2722debac09f158aed31fb4/r/o/romeo-y-julieta-fabulosos-no.-2-2016-4.jpg",
        };

        public static readonly Dictionary<string, string> BrandDescription = new Dictionary<string, string>
        {
            {
                "QUAI-DORSAY", @"Quai d'Orsay is the name of a premium cigar brand, produced on the island of Cuba for Habanos SA.
The Quai d'Orsay brand was created by Cubatabaco in 1973 for the French state tobacco monopoly, SEITA, and was blended with French tastes in mind, being a milder brand. There are a few competing stories as to what the marque's name refers to: one is that it is referring simply to the famous Paris avenue, another is that it refers to the French Foreign Ministry that is located on it, and another is that it is referring to the headquarters of SEITA which is also on the same avenue.
Quai d'Orsay was apparently outside of the umbrella of Habanos SA for a number of years and was managed directly by Cubatabaco and SEITA, but judging by packaging, Habanos SA documents, and SEITA's merger with Tabacalera into the multi-national tobacco company of Altadis, it appears Quai d'Orsay is a part of Habanos SA like all other Cuban-made brands of cigars.
Another oddity of the Quai d'Orsay line are its Corona cigars. Up until the late 1980s, Quai d'Orsay still manufactured its Coronas in two different wrapper shades: Claro and Claro Claro. As the fashion for lighter wrappers diminished (and supposedly as consumers noticed they were paying more for essentially the same cigar with the wrapper making a very minor difference) production eventually ceased of the Coronas Claro Claro. Though the box still says Coronas on it, the official production name is still Coronas Claro.The following list of vitolas de salida (commercial vitolas) within the Quai d'Orsay marque lists their size and ring gauge in Imperial (and Metric), their vitolas de galera (factory vitolas), and their common name in American cigar slang."
            },
            {
                "TRINIDAD", @"Trinidad is a Cuban brand of cigars, named for the city of Trinidad. Cigars are manufactured in Cuba by Habanos S.A. and in Dominican Republic by Spanish Altadis, a subsidiary of Imperial Brands.According to Adriano Martinez, a former executive of Habanos S.A. giving testimony in Min Ron Nee's Illustrated Encyclopedia of Post-Revolution Havana Cigars, the Trinidad brand was first produced in 1969 at the El Laguito factory in Havana.In the early 1990s, the cigar received much attention in Cigar Aficionado after an interview with Avelino Lara (formerly the manager of El Laguito, and a producer of cigars for the Graycliff Hotel in Nassau, Bahamas until his death on October 27, 2009). In the 1992 interview, Lara claimed that Trinidad was an ultra-exclusive brand that only Fidel Castro was authorized to hand out as diplomatic gifts. Lara also claimed Trinidads were of a higher quality than the much-lauded Cohibas that had formerly been diplomatic exclusives before their mass-market release in 1982.Two sources have contradicted Lara's claims: President Fidel Castro himself and the afore-mentioned Mr. Martínez. In an interview with Cigar Aficionado, when asked about Trinidads, Castro stated that he only gave Cohibas away as diplomatic gifts, and in his autobiography; my life, he claims to know very little of the Trinidad brand. In the Illustrated Encyclopedia, Martínez stated that Trinidads were actually a lower-level diplomatic gift than Cohiba cigars, made with a tobacco blend similar to that used in the Cohiba vitolas, but without the third barrel fermentation that Cohibas receive.In 1995, Cigar Aficionado hosted the Dinner of the Century in Paris, France, where, among other rarities, the guests became the first outside of diplomatic circles to taste Trinidad cigars.In February 1998, the Trinidad brand was released for public consumption at an opening ceremony in the Habana Libre Hotel in Havana.The initial release was only in one size: the Fundador.Though Martínez and others maintain that the blend did not change in the transition from a diplomatic gift to a mass-marketed cigar, the size did.The diplomatic Trinidads only came in one size, that of a Laguito No. 1 (the same as the Cohiba Lancero). The Fundador instead comes in a new size with a factory name of Laguito Especial, the same length as a Laguito No. 1 but with a ring gauge of 40 instead of 38.In November 2003 at a black tie dinner hosted by British importer Hunters & Frankau at the Hilton Park Lane in London, England, three new sizes were debuted for the Trinidad line: the Coloniale, the Reyes, and the Robusto Extra."
            },
            {
                "SAN-CRISTOBAL", @"San Cristobal de la Habana is the name of a Cuban cigar brand produced in Cuba for Habanos SA, the Cuban state-owned tobacco company.San Cristobal de la Habana was officially launched in Havana on November 20, 1999. It was named after the original name of Havana which dates back to the 16th century.Before the Revolution, a brand by the name of San Cristobal de la Habana existed, and it was produced until the Revolution. However, this new brand is completely unrelated and not a resurrection of the old brand.The brand initially launched with 4 cigars (El Morro, El Principe, La Fuerza, and La Punta). In 2004, to celebrate the brand's fifth anniversary, 3 additional cigars were produced for the V Anniversary Humidor and eventually released for public sale. These new cigars, the Officios, Mercaderes and Muralla, also feature an additional La Casa del Habano band as these cigars were only available at La Casa del Habano retailers."
            },
            {
                "ROMEO-Y-JULIETA", @"Romeo y Julieta is a brand of premium cigars, currently owned by Imperial Brands. Cigars are currently owned by two Imperial Brands subsidiaries, Habanos S.A. in Cuba and Altadis in the Dominican Republic.
The Romeo y Julieta marque was established in 1875 by Inocencio Alvarez and Manin García. The brand is the Spanish name for Shakespeare's famous tragedy, Romeo and Juliet.
Between 1885 and 1900, the brand won numerous awards at different tasting exhibitions (as still evidenced by the gold medals on the brand's logo). However, the brand truly bloomed after it was acquired by José Pepin Rodriguez Fernández, former head of the Cabañas factory in Havana, and his firm, Rodríguez, Argüelles y Cia, in 1903. Being a very cosmopolitan man, Rodriguez constantly travelled across Europe and the Americas, actively promoting his brand, and entering his horse, the aptly named Julieta, in racing events across the world.
As a result of his salesmanship, the brand became exceptionally popular around the world among wealthy customers, many of whom demanded personalized bands for their cigars. At its height, as many as 2000 personalized cigar bands were produced for customers. The branded was also known at this time for specializing in figurado cigars, such as perfectos and pirámides, with over a thousand such shapes believed to have been in production.
Sir Winston Churchill was perhaps the brand's most famous devotee. The flagship vitola of the brand is named in his honor, a long 7inch by 47 ring gauge cigar known as the Churchill.
After Rodriguez's death in 1954 (he was 88 years old), the revolution, and the subsequent nationalization of the tobacco industry, the brand was moved to La Romana in the Dominican Republic, where production of a Romeo y Julieta cigar for the American market continues today under the direction of Altadis SA. The Cuban government nationalized the brand and still produces and distributes it worldwide as one of its top-selling global brands.
"
            },
            {
                "RAMON", @"Ramón Allones is the name of two premium cigar brands, one produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company, and other produced in Honduras for General Cigar Company, now a subsidiary of Swedish Match.
The brand was created in Cuba by brothers Ramón and Antonio Allones (no relation to the Antonio Allones of El Rey del Mundo fame) in 1845 and is supposedly the first cigar brand to have utilized colorful lithographs for box art, the first brand to utilize bands on cigars, and the first to package cigars in the 8-9-8 style (though there are several rival claimants as to who first made box art and bands).
The brand went through numerous ownership changes before it was finally bought by the Cifuentes family and production was moved to the famous Partagás Factory, where Ramón Allones cigars are still made to this day.
On September 15, 1960, the revolutionary Cuban government nationalized all Cuban cigar manufacturing and production, including seizure of the Partagas factory where Ramon Allones cigars were manufactured. The Ramon Allones brand was selected for continued production and continues to be manufactured in Havana. Cuban-made Ramon Allones cigars use are medium-full to full strength in body, and the blend shares some of the characteristics of Partagás as far as overall body, vitolas, and packaging. It has always been produced in smaller quantities than Partagás.
Since 2001, when Altadis bought a controlling share of Habanos SA, the Ramón Allones marque has seen the majority of its manufactured sizes discontinued, including the much-beloved Coronas and even the 8-9-8 size it helped pioneer. Of the sizes available now, the Specially Selected, Gigantes, and Small Club Coronas are still incredibly popular among aficionados.
Since 2005, Ramón Allones has been a popular choice with many importers for the Edición Regional series of local market special sizes. The Belicoso vitola released for the UK market may have been a prototype for the regional edition program, as it appeared first, being imported only to the UK, and without any additional bands or special packaging.
"
            },
            {
                "DAVIDOFF", @"Davidoff is a Swiss premium brand of cigars, cigarettes and smoker's accessories. The Davidoff cigarette brand has been owned by Imperial Brands after purchasing it in 2006. The non-cigarette portion of the Davidoff tobacco brand is owned by Oettinger Davidoff AG, which is based in Basel, Switzerland.
Oettinger Davidoff AG manufactures a broad portfolio of cigars, cigarillos, pipe tobaccos and smoker's accessories under the brands Davidoff, Camacho and Zino Platinum. The cigars are produced in the Dominican Republic and Honduras, and tobacco is sourced from the Dominican Republic, Nicaragua, Brazil, Peru, Mexico, Ecuador, Honduras and the United States of America.
After the Second World War, Zino Davidoff decided to acquire a license to produce his own series of cigars. As he had discerning international customers, he named the various formats of this Château” cigar series after famous Bordeaux vineyard estates. The first in the series was the Château Latour in 1946.
In 1967, Zino Davidoff was approached by Cubatabaco, Cuba's state tobacco monopoly, about creating a line of cigars carrying the “Davidoff” name. The cigars were rolled in the newly established El Laguito factory in Havana, which had been established to roll Cuban President Fidel Castro's own personal cigars, named Cohíba.
In 1968, the first cigars carrying the name Davidoff were released. The first formats were the No. 1, the No. 2 and the Ambassadrice. In 1970, Oettinger AG, located in Basel, Switzerland, acquired the rights to the Davidoff trademark.
In 1971, the Davidoff Mini Cigarillos (short fillers made of 100% tobacco) and, in 1972, the first Davidoff pipe tobaccos were released. As of 1975, the cigars of the Château series were delivered in cabinets bearing the Davidoff logo.
In 1976, the Mille Series and, in 1977, the Dom Pérignon cigar, named after the champagne, were released. In 1986, a limited release of Anniversario cigars were produced, to celebrate Zino Davidoff's 80th birthday.
The Zino Davidoff Group was spun out of Davidoff in 1980 to exclusively market non-tobacco luxury goods such as watches, leather goods, pens, fragrances, eyewear, coffee, and cognac. Public health researchers have suggested that this was in order to engage in trademark diversification (also known as brand stretching) to promote the tobacco products, because it allows for advertising the brand in the face of restrictions on the direct promotion of tobacco products.
After numerous disputes over quality and ownership rights, Zino Davidoff and Cubatabaco decided to end their relationship. Leading up to this, in August 1989, Zino had publicly burned over one hundred thousand cigars that he had deemed of low quality and unfit to sell. All Davidoff products produced in Cuba were officially discontinued in 1991. An agreement was signed that no more Davidoff cigars from Cuba would be sold.
In 1990, after discontinuing Cuban-made products, Davidoff started to produce cigars in the Dominican Republic. After numerous test runs, Zino Davidoff found a partner in the local producer “Tabadom”, owned by Hendrik Kelner.
In 1991, the first Dominican-made Davidoff cigars were launched, continuing the product lines and cigar formats of their Cuban predecessors. With the move to the Dominican Republic, the Château series was renamed to “Grand Cru”, and the individual formats were numbered instead of carrying the names of vineyard estates.
In 1991, the limited release called “Aniversario” became an ongoing cigar series, called the “Aniversario” series. In 1992, the “Special” cigar series was released, with the format “Special R” as the first product. In 1994, the 87 year old Zino Davidoff died in Geneva, Switzerland. In 2001, the “Millennium Blend” cigar series was launched. In 2010, Davidoff Cigars released the “Puro d’Oro” series.
In 2013, Davidoff Cigars released the “Nicaragua” series, which was the first product line of Davidoff to incorporate tobaccos from Nicaragua into the cigar blend, and the first series since the Davidoff Cuban products which made use of tobaccos not sourced in the Dominican Republic. Moving forward, Davidoff Cigars started to make use of tobaccos sourced from other countries than the Dominican Republic to diversify their product portfolio.
In 2015, Davidoff Cigars released the “Escurio” series, which contained tobaccos sourced from Brazil. In the same year, the cigar line “Winston Churchill” was launched. In 2016, Davidoff Cigars released the “Yamasa” cigar series.
"
            },
            {
                "QUINTERO-BREVAS", @"Quintero is a brand of premium cigars, owned by British conglomerate Imperial Brands. The brand is produced in Cuba by Habanos S.A., the local state-owned tobacco company, which also owns the brands Cohiba, Montecristo, and Romeo y Julieta.
The Quintero cigar brand was created as Quintero y Hermanos or Quintero and Brothers, when Agustin Quintero and his four brothers opened a small cigar factory in the town of Cienfuegos, Cuba in 1924 and began producing a handmade cigar. Cienfuegos, a city on the southern coast of Cuba, is located near the Vuelta Arriba of the Remedios tobacco growing region, and the brand is one of the few Cuban cigar brands not born in the heartland of the prime tobacco growing region of Vuelta Abajo.
The Quintero brand and its blend of tobacco quickly became commercially successful both in Cuba and abroad, and the Quintero brothers soon developed several sizes of cigars. By the 1940s, Quintero y Hermanos had opened a much larger rolling factory in Havana, and had begun using prime tobaccos from the Vuelta Abajo region.The brand continued to grow in sales, and was particularly popular in Spain.
It the early 1960s, after Fidel Castro nationalized the Cuban cigar industry, the Quintero brand was repositioned as a primarily machine-made cigar, and most of the handmade sizes were dropped in favor of machine-made or hand-finished cigars using short filler tobaccos, sometimes sold in aluminum tubes or tubos.For many years, Quintero was the only Cuban machine-made brand to be globally marketed by Habanos SA.As before, a large part of Quintero production went to Spain.Unusual among Cuban cigars, the Quintero cigar blend is noted for a herbal flavor with sweet aftertaste. The cigars generally benefit from several months of additional aging before smoking.
"
            },
            {
                "BOLIVAR", @"Bolívar is the name of two brands of premium cigar, one produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company, and the other produced in the Dominican Republic from Dominican and Nicaraguan tobacco for General Cigar Company, which is today a subsidiary of Scandinavian Tobacco Group. Both are named for the South American revolutionary, Simón Bolívar.
The Cuban-produced Bolívar cigars are very full-bodied, with considerable ligero in the blend and have traditionally been some of the strongest and most full-bodied Havana cigars.
The brand was founded (possibly in Great Britain) by José F. Rocha around 1901 or 1902, though the brand was not registered in Havana (Cuba) until 1921, under the ownership of Rocha's firm, J.F. Rocha y Cia.
During this time, the Bolívar brand produced the world's smallest cigar called the Delgado. Measuring a mere 17⁄8 inches with a 20 ring gauge, the Delgado had the honor of having a miniature box of its cigars featured in the royal nursery's dollhouse at Windsor Castle.
The company and rights to the brand name were purchased in 1954 by Cifuentes y Cia after Rocha's death and production was moved to the famous Partágas Factory in Havana (today known as the Francisco Pérez Germán factory), where many of its sizes are still produced today.


The Cuban Bolívar has a reputation among cigar aficionados of being one of the strongest and most full-bodied cigars, with its Royal Corona, Coronas Junior, Petit Coronas, and Belicosos Finos being famous examples of the marque. In 2002, when Altadis bought a controlling share in the Cuban government-owned cigar distributor, Habanos SA, a number of changes in cigar production were instituted. One of these changes was the decision to gradually turn the various brands of Cuban cigars to either all-handmade or all-machine-made lines. Bolívar, which has historically produced a variety of handmade and machine-made or machine-finished cigars, had several of its vitolas cut from production, with only one remaining, the cigarillo-sized Chicos. It remains to be seen if this size will eventually cease to be produced as well.
In 2004, Wolters in Cologne, Germany, had a few thousand boxes of Bolívar Gold Medals produced by Habanos SA exclusively for their shop. The cigars are an older, discontinued Bolívar size in the Cervantes (lonsdale) format, wrapped in gold foil on one half with a special Bolívar band in the middle and come packaged in boxes of ten. Following this release the Gold Medal was reinstated in 2007 as a LCDH cigar but was then discontinued in 2011.
The Bolívar brand has also been chosen several times for special sizes in regional releases.
"
            },
            {
                "COHIBA", @"Cohiba is a brand for two kinds of premium cigar, one produced in Cuba for Habanos S.A., the Cuban state-owned tobacco company, and the other produced in the Dominican Republic for US-based General Cigar Company. The name cohíba derives from the Taíno word for tobacco.The Cuban brand is filled with tobacco that comes from the Vuelta Abajo region of Cuba which has undergone an extra fermentation process. Cuban Cohiba was established in 1966 as a limited production private brand supplied exclusively to Fidel Castro and high-level officials in the Communist Party of Cuba and Cuban government.Often given as diplomatic gifts, the Cohiba brand gradually developed a cult status.It was first released commercially for sale to the public in 1982. The Cohiba Siglo VI has received some of the highest scores in the line from blind reviews, including a 93 from Cigar Aficionado and a 90 from Blind Man's Puff.The US Cohiba brand name was registered in the United States by the General Cigar Company in 1978 and cigars using that trademark have been produced for the American market in the Dominican Republic on a large scale from 1997. This Cohiba is related to the Cuban product in name only, containing no Cuban tobacco, and thus is the only Cohiba that can be sold legally in the United States.Cuban Cohibas have historically been known to use some of the finest cigar tobacco available in Cuba.The tobacco for Cohiba is selected from the finest Vegas Finas de Primera(first-class tobacco fields) in the San Luis and San Juan y Martinez zones of the Vuelta Abajo region of Pinar del Río Province.In 1992 just 10 carefully selected fields totaling about 700 acres were used for production of the Cohiba brand, their exact location a carefully guarded trade secret. The production of these fields is further selected for quality, with the output of just five of these fields used in Cohiba production in an average year.The tobacco used to fill the cigars is unique among Cuban brands owing to a special third fermentation in wooden barrels at the El Laguito factory, aimed at producing a smoother flavor than other cigars. Originally all Cohibas were made at the El Laguito factory, a mansion located on the outskirts of Havana converted into a cigar-rolling school for women in 1961. Production of some Cohiba vitolas was later expanded to the Partagas factory in Havana, which manufactures its Cohiba product from pre-blended tobacco received from El Laguito.Cohiba cigars tend to be medium to full-bodied in flavor."
            },
            {
                "CUABA", @"Cuaba is the name of a Cuban cigar brand produced in Cuba for Habanos SA, the Cuban state-owned tobacco company.
Cuaba was officially launched by Habanos president Francisco Linares on November 19, 1996, at Claridge's Hotel in London, Great Britain, as an all-perfecto line of cigars. The brand was launched in an attempt to revive figurados, which had initially been very popular in the early 20th century but had declined since about the 1950s. For the release party, the creator of the line, Carlos Izquierdo González, and fourteen other highly skilled torcedores (cigar rollers) demonstrated making figurado cigars. The original Cuabas were of slightly differing sizes within the same box, due to a cigar mold not being used to press them into shape. When molds were finally made for Cuaba around a year later, these original non-molded cigars became great collectors' items.
González claims he styled the Cuaba blend after Montecristo, but most cigar connoisseurs believe the blend used is more similar in taste to Romeo y Julieta. Unsurprisingly, most Cuaba cigars are manufactured in the Briones Montoto (Romeo y Julieta) factory.
In 1998, Cuaba had the distinction of being one of the cigar brands chosen to be released with a special vitola (the Distinguidos) in a Millennium Reserve ceramic jar humidor and is often a brand chosen for special releases and humidors.
"
            },
            {
                "DIPLOMATICOS", @"Diplomáticos is the name of a premium cigar brand, produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company, at the José Martí factory in Havana.
Diplomáticos was the first new brand of Cuban cigars after the Cuban Revolution produced commercially for public sale (the Cohiba was the very first brand created post-Revolution, but was only used for President Fidel Castro's private consumption and for diplomatic gifts, and was not sold on the commercial market until 1982).
Diplomáticos was created in 1966 from the Montecristo, and featured a slightly milder blend and lighter shade wrapper intended to appeal to the French consumer. The Diplomáticos line mimics the original Montecristo line in having five numbered sizes, all handmade, but priced slightly less than the equivalent-size Montecristo cigar. Today, both Diplomaticos and Montecristo are produced at the José Martí Factory. Diplomaticos continue to utilize a medium-strong long-filler blend from the Vuelta Abajo region slightly milder than that of the cigars from the Montecristo line, but otherwise equal in terms of quality.
The original line consisted of five numbered sizes, corresponding to Montecristo. In 1976, the No. 6 and No. 7 were introduced to the line and were the same size as the Montecristo Especial No. 1 and Especial No. 2, but were discontinued a few years later in the mid-1980s.
"
            },
            {
                "EL-REY-DEL-MUNDO", @"El Rey del Mundo is the name of two premium cigar brands, one produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company, and other produced in Honduras by the Villazon family.
Believed to have been created, along with Sancho Panza, by German businessman Emilio Ohmstedt in 1848, El Rey del Mundo (King of the World in Spanish) was at one time the most expensive and prestigious cigar brand in the world.
Spanish businessman Antonio Allones took over the brand sometime around 1882 (a rival version of the brand's history claims the brand became defunct after Ohmstedt's death and Allones re-registered it, but cigar connoisseur Min Ron Nee maintains the brand was passed to Allones from Ohmstedt's company, based on records stating Allones as the owner of El Rey del Mundo from as early as 1873). Under Allones, the brand reached the height of its worldwide prestige. In 1905, Allones' company was bought by the Díaz Hermanos y Cía venture, owned by Cándido Vega Díaz (supposedly the namesake of Don Cándido cigars), which was later renamed the Rey del Mundo Cigar Co. to reflect its most famous asset. Production moved to a factory at 852 Calle Belascoain in Havana. The company also produced such famous brands as Sancho Panza, Rafael González, and Don Cándido.
Production continued after the Revolution and the brand maintained its popularity through the 1960s and 1970s, but as the world taste started to run towards stronger cigars, the milder El Rey del Mundo brand began to lose its status as a foremost brand of Cuban cigars. Despite its loss of popularity, El Rey del Mundos cigars are still prized for their mild, complex flavors, with the Choix Supreme, Grandes de España, and Demi Tasse sizes being particularly popular among connoisseurs.
"
            },
            {
                "FONSECA", @"Fonseca is the name of two brands of premium cigar, one produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company, and the other produced in Nicaragua by Don Pepin Garcia's My Father Cigar brand.
Don Francisco E. Fonseca was born in Manzanillo, Cuba, in 1868 (or possibly 1869 or 1870; the documents differ), and established a factory and his own cigar brand in Havana in 1892. He registered the brand bearing his name in 1907. Fonseca and his wife Teresa Boetticher de Fonseca immigrated to New York and by 1903, Fonseca was operating a factory at 169 Front Street. He became an American citizen in 1895 and by 1905 the registry of cigar factories lists F.E. Fonseca & Co. in a new location: 129 Duane Street (court documents specify 148-150-152 Duane Street, in Tribeca). In New York, at his home at 48 West 73rd St., he and Teresa raised four children - three of whom he named Francisco. Fonseca made frequent trips to Cuba, where he supervised “F.E. Fonseca. Fábrica de Tabacos y Cigarros”. His business stationery reflects his double loyalty, depicting both the Statue of Liberty and the Morro, Havana.
Fonseca cigars quickly became a success. Besides having a reputation for selecting the finest quality tobacco, Don Francisco developed an innovative method of packaging his cigars, wrapping each one separately in a tube of tin foil, and then an outer covering of fine Japanese paper, so as to shield the cigar from atmospheric changes. (They are still packaged this way today, with the tubes now usually made of aluminum foil instead of tin.) After Don Francisco's premature death of a heart attack, in Havana, in 1929,his wife Teresa continued the business and merged the brand with T. Castañeda and G. Montero to form the firm of Castañeda, Montero, Fonseca SA.
Production continued uninterrupted after the revolution and the cigars are still produced at the Lázaro Pena Factory in Havana. As a cigar brand, Fonseca is relatively mild by most aficionados' standards, sells for cheaper than most other Cuban cigar brands, and is marketed mostly in Spain and Canada, where the brand is particularly popular.
"
            },
            {
                "HOYO-DE-MONTERREY", @"Hoyo de Monterrey is the name of two brands of premium cigar, one produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company and the other produced in Honduras by General Cigar Company, now a subsidiary of Swedish Match.
In 1831, Don José Gener y Batet emigrated to Cuba from Spain at the age of thirteen, where he worked on his uncle's plantation in Vuelta Abajo. Twenty years later, he would open his own cigar factory in Havana and begin producing his own cigar line, La Escepción. In 1865, after using his factory's profits to acquire one of the best tobacco farms in Vuelta Abajo, he registered a cigar line named for it: Hoyo de Monterrey.
Literally translated from Spanish to English as the Hole of Monterrey in reference to the concave terrain favoured by growers of premium tobacco, the brand became incredibly popular, especially in the British market and José Gener's factory subsequently became one of the largest factories in Cuba. In 1900, Gener died in Spain and his daughter Lutgarda Gener took over the business and it would stay in the family for another thirty years.
In 1931, the Gener family sold their cigar brands in order to focus more on their sugarcane properties. The firm of Fernández, Palicio y Cía bought the Hoyo de Monterrey and La Escepción brands and added them to their impressive line-up, which already included Punch and Belinda. Around this time, in the 1940s, the Le Hoyo series (along with the Chateaux series which would later be used to create the Davidoff cigar line) was created for Swiss distributor A. Dürr Co. After the death of partner Ramón Fernández, Fernando Palicio became sole proprietor of the business and by 1958 his cigar lines accounted for 13% of all Havana cigar exports.
After the revolutionary government of Cuba unilaterally nationalised all the cigar manufactures in 1959, Fernando Palicio voluntarily left Cuba for Florida. He subsequently sold his cigar lines to the Villazon family, which continued to make Punch, Hoyo de Monterrey and Belinda cigars in their Tampa, Florida factory from Honduran tobacco for the American market.
Hoyo de Monterrey continued production in Cuba and in Honduras and is still a popular, globally marketed Cuban cigar line. Among connoisseurs, the Epicure No. 2, Double Coronas and Le Hoyo series are particularly prized.
Being a globally marketed brand, Hoyo de Monterrey has been chosen for Habanos' annual Edición Limitada releases since 2000. The Particular had some production problems during the first Edición Limitada line-up in 2000, with few of the cigars getting out to vendors. This prompted Habanos to release it again the next year, the only Edición Limitada cigar so far to have had this."
            },
            {
                "H.UPMANN", @"H. Upmann is a Cuban brand of premium cigars established by banker Hermann Dietrich Upmann (who also founded the H.Upmann & Co. bank in the island). The brand is currently owned by British corporation Imperial Brands. Cigars are manufactured by Habanos S.A. –the state-owned tobacco company– in Cuba, and Altadis in La Romana, Dominican Republic.
H. Upmann is among the oldest cigar brands in existence. In 1843, banker Hermann Dietrich Upmann (16 May 1816 – 1894) arrived in Havana, Cuba, to arrange business affairs for the firm of Gravenhorst & Co., an importing/exporting firm located in Bremen, Germany. Seeing the potential for further importing opportunities, Upmann purchased a local cigar factory at 85 San Miguel Street, Havana, and began producing cigars under the H. Upmann brand in 1844.At the same time he began a banking business, initially catering to tobacco dealers and manufacturers.Hermann Upmann retired in 1890, and was succeeded by his nephew, Heinrich Upmann, who continued operating the business with his partners Heinrich Runken and Theodore Garbade,[until his death in 1914, and was in turn succeeded by Hermann and Albert (Alberto) Upmann, nephews of Heinrich.By 1900, H. Upmann cigar manufacturing had moved to a large building located at 159-169 Paseo de Tacon (later renamed Avenida Carlos III) in Havana, sited between Calle Belascoin and Avenida Carlos III (Tercero). The H. Upmann Bank was at Calle Mercaderes Amargura 1-3 in Havana.
Upmann is sometimes credited with the invention of packaging cigars in cedar boxes to give to their customers. These original boxes were labelled with the H. Upmann name and contained other manufacturers' cigars, most likely as an advertisement for the operation, until the Upmanns bought their own cigar factory in 1844: the famous H. Upmann Factory, now known as the José Martí Factory, in Havana.
Through the late 1800s, the H. Upmann brand gained international recognition at various exhibitions and won seven gold medals which still adorn the lithographed art on today's H. Upmann boxes, along with Hermann Upmann's original signature. In North America, Charles Landau became the exclusive agent for H. Upmann cigars for many years
"
            },
            {
                "JOSE-L.-PIEDRA", @"José L. Piedra sind besonders bemerkenswerte Habanos, denn die verwendeten Blätter entstammen ausschließlich der Tabakanbauregion Vuelta Arriba.
Die Familie Piedra siedelte in den 80er Jahren des 19. Jahrhunderts aus der spanischen Provinz Asturien nach Kuba um. Sie liess sich in der Nähe der Stadt Santa Clara nieder, die im Herzen der Region Vuelta Arriba liegt, wo seit dem 16. Jahrhundert Tabak angebaut wird, und begann dort mit der Zigarrenherstellung.
Die von José Lamadrid Piedra angeführte zweite Generation gründete und entwickelte die Marke, wie wir sie heute kennen. Ihre Zigarren sind robust und preisgünstig. Sie werden wegen ihrer kräftigen Würze geschätzt.
Alle sechs Formate der José L. Piedra werden im traditionellen ‘totalmente a mano, tripa corta’ Verfahren hergestellt - vollständig von Hand gefertigte Shortfiller."
            },
            {
                "JUAN-LOPEZ", @"Juan López is the name of a cigar brand produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company.
n 1876, Juan López Sena (aka Juan López Diaz) created the Juan López brand. producing cigars in Havana on Calle de los Dragones. In 1908, the brand was passed to his heirs, and was then sold to the Sociedad Cosme Del Peso y Cía in 1918, which owned the brand until the Cuban revolution. During its history, the brand has also been labeled Flor de Juan López, only to return to the original name in time.
In September 1960, the Cuban revolutionary government nationalized the Cuban cigar industry and seized the factory where Juan López cigars were manufactured. Production was resumed, and today all Juan López cigars are made by hand (totalmente a mano) at the La Habana factory in Havana
"
            },
            {
                "MONTECRISTO", @"Montecristo a brands of premium cigars and cigarrettes, produced in Cuba by Habanos S.A., the local tobacco company, and in La Romana, Dominican Republic by Altadis, a subsidiary of British conglomerate Imperial Brands.
In July 1935, Alonso Menéndez purchased the Particulares Factory, makers of the popular Particulares brand and the lesser-known Byron. Immediately after its acquisition, he created a new brand named Montecristo.
The name for the brand was inspired by the Alexandre Dumas, père novel The Count of Monte Cristo, which was supposedly a very popular choice among the torcedores (cigar rollers) in their factory to have read by the lector on the rolling floor. The now-famous Montecristo logo, consisting of a triangle of six swords surrounding a fleur-de-lis, was designed by John Hunter Morris and Elkan Co. Ltd., the brand's British distributor.
In July 1936, Menéndez founded a new firm with a partner, naming it Menéndez, García y Cía. With the growing success of the Montecristo brand, the firm purchased the faltering H. Upmann Factory (created by Hermann Dietrich Upmann in 1844) from J. Frankau SA in 1937 and transferred Montecristo production there. J. Frankau continued as sole distributor of the H. Upmann brand in the UK, while John Hunter Morris and Elkan Co. Ltd. was the sole distributor of Montecristo in Britain. In 1963, these firms merged to become Hunters & Frankau, which today is the sole importer and distributor of all Cuban cigars in the UK.
Through the efforts of Alfred Dunhill (the company), the Montecristo brand became incredibly popular worldwide and to this day accounts for roughly one-quarter of Habanos SA's worldwide cigar sales, making it the most popular Cuban cigar in the world. Menéndez and García fled during the Cuban Revolution, and on September 15, 1960, after which the Montecristo brand, the factory, and all assets were nationalized by the government of Fidel Castro.
Menéndez and García re-established their brand in the Canary Islands, but were later forced to quit due to trademark disputes with Cubatabaco (later known as Habanos S.A.). In the mid-1970s, the operation was moved to La Romana and released for the US market, since Cuban government rights to the brand were not recognized under American law due to the 1960 nationalization and subsequent embargo. Menéndez, García, y Cía is now owned by Altadis S.A., who controls its distribution and marketing in the United States.
With Menendez and Garcia gone after 1959, one of the top grade torcedores, José Manuel González, was promoted to floor manager and proceeded to breathe new life into the brand. In the 1970s and 1980s, five new sizes were added: the A, the Especial No. 1 and 2, the Joyita, and the Petit Tubo. Three other sizes, the Montecristo No. 6, No. 7, and B, were released but subsequently discontinued, though the B can occasionally be found in very small releases each year in Cuba. Through the 1970s and 1980s, Montecristo continued to rise in popularity among cigar smokers, becoming one of Cuba's top selling cigar lines.
"
            },
            {
                "PARTAGAS", @"Partagás is the brand name of two lines of cigars made by two independent and competing entities, one produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company; the other, containing no Cuban tobacco, produced in the Dominican Republic for General Cigar Company, a division of Scandinavian Tobacco Group of Denmark.
The Cuban version is the original and among the oldest extant cigar brands, established in Havana in 1845.
The Catalan Don Jaime Partagás y Ravelo (Arenys de Mar, 1816 - Vuelta abajo, Cuba, 1868) was the son of Jaume Partagás (tailor) and Teresa Ravelo. He migrated to Cuba in 1831 and worked for Lloret de Mar businessman, Joan Conill in Havana. Establishing his own factory, La Flor de Tabacas de Partagás in 1845, at 1 Cristina St. in Havana (later relocated to Calle Industria), Don Jaime owned many of the best plantations in the Vuelta Abajo tobacco-growing region of Cuba. Don Jaime's ability to choose from among the finest tobaccos on the island, and an instinct for blending and fermenting tobaccos made the brand incredibly successful. Don Jaime is also legendarily credited with hiring one of the first lectors to read to and entertain the cigar rollers as they worked.
Don Jaime was murdered on one of his plantations in 1868 and his son José Partagás took over the business. Later the factory and brand were sold to banker José A. Bances. In 1899, Bances invited Ramón Cifuentes Llano (1854-1938), a talented tabaquero from Ribadesella Spain – to join him as partner. Bances sold his remaining shares to Cifuentes the following year. Cifuentes took over management of Partagás with José Fernández López and was joined in 1916 by the Galician vegas owner and leaf wholesaler, Francisco Pego Pita, who in turn sold the company to Cifuentes, Fernández y Cía in 1900. In 1916, Don José Fernández left the firm and Ramón Cifuentes Llano joined with Francisco Pego Pita to form Cifuentes, Pego y Cía. In 1927, it acquired the rights to the Ramón Allones brand; at some unknown point the factory began to produce a brand in its own name, Cifuentes.
Ramón Cifuentes Llano died in 1938 and Pego in 1940, leaving his three sons in charge of Partagas. Ramón Cifuentes Toriello and his two brothers continued to build the increasingly prestigious factory and brand, and renamed the company Cifuentes y Cía. In 1954, the Cifuentes family acquired the Bolívar and La Gloria Cubana brands from José F. Rocha and moved their production to the Cifuentes factory. By 1958 Partagás was second only to the H. Upmann company in exporting Cuban cigars, accounting for over a quarter of all exported tobacco goods.
On September 15, 1960, Fidel Castro's revolutionary Cuban government seized 16 cigar factories, including the Partagas factory and related assets. At 6:30PM, soldiers entered the Partagas fabrica and encountered Ramón Cifuentes Toriello. They came inside and said, We are here to intervene the company, Cifuentes recalled in 1991. And they didn't allow me to take anything from there. The Partagás brand was later selected for continued production under Cuban state government control, first by Cubatobaco and later Habanos S.A.
Before and after the Cuban Revolution, the Cuban-produced Partagás has continued to be one of Cuba's best-selling cigar brands. By the middle 1990s it was second in sales only to Montecristo, with annual sales of approximately 10 million cigars.
The old Partagás Factory in Havana, since renamed Francisco Pérez Germán, was responsible for the production of much of the brand until it was relocated 3km from Havana Vieja. A new factory now produces most vitolas. Both locations are popular tourist destinations for cigar smokers vacationing in Cuba. The move to the new factory took place on January 2, 2012.
In 2002, Altadis bought a controlling share in the Cuban government-owned cigar distributor, Habanos SA, and instituted a number of changes in cigar production. Among them was gradually turning the various brands of Cuban cigars to either all-handmade or all-machine-made lines, reducing the number of redundant sizes within a brand, and eliminating many low-selling cigars. Many of Partagás lesser-known handmade and all machine-made cigars were cut from production. Today, all Cuban Partagás cigar vitolas are hand-made.
Since the introduction of the Edición Limitada annual releases, Partagás has produced a special size almost every year: the Pirámide in 2000, the Serie D No. 3 in 2001, the Serie D No. 2 in 2003, the Serie D No. 1 in 2004, a reissue of the Serie D No. 3 in 2006, and the Serie D No. 5 in 2008. In 2005, Partagás introduced a pyramid, the Serie P No. 2.
Partagás also offers two machine-made cigarillos, (the Mini and the Club), as well as a branded cigarettes.
"
            },
            {
                "PUNCH", @"Punch is the name of two brands of cigars, one produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company, and the other produced in Honduras for General Cigar Company.
The Punch brand was first registered in 1840 by German named Stockmann and named for the European puppet show character, Mr. Punch (not the magazine, which was created a year later). The brand quickly became a success, especially in Great Britain. The first change of ownership came in 1874, when the brand was bought by a Luis Corujo, and again in 1884, when the brand was purchased by Manuel López Fernández and its bands and boxes still bear his name to this day. Retiring in 1924 and dying shortly after, López gave ownership of the brand to Esperanza Valle Comas, who only held it for a few years before the Stock Market Crash of 1929.
Like most other businesses around the world, the Cuban cigar industry faced financial hardships. In 1930, the firm of Fernández, Palicio y Cía bought up the brand, where it became one of the company's headlining cigar marques, along with Belinda, La Escepción, and Hoyo de Monterrey, and maintained its popularity with British cigar smokers.
After the embargo was set against Cuba by the United States, Fernando Palicio fled Cuba for Florida, where he subsequently sold his cigar lines to Frank Llaneza and Dan Blumenthal of Villazon & Co., which has continued to make Punch, Hoyo de Monterrey, and Belinda cigars from Honduran tobacco for the American market.
Cuba subsequently nationalized the tobacco industry and Punch continued production and is still a popular, multi-locally-marketed Cuban cigar line. Among connoisseurs, the eponymous Punch, Double Corona, Churchill, and Super Selection No. 2 are especially prized and sought after.
Punch also produces two machine-made cigarillos: the Cigarritos and Cigarritos Reserva.
Punch has two Edición Limitada production cigars. One was released in 2013, and the other in 2017. It is also extremely popular as a brand for the Edicion Regional series of cigars produced by Habanos for local markets.
"
            },
            {
                "VEGAS-ROBAINA", "Vegas Robaina is the name of a premium cigar brand, produced on the island of Cuba for Habanos SA, the Cuban state-owned tobacco company. Alejandro Robaina was renowned by cigar aficionados everywhere as one of the best tobacco farmers in the famed Vuelta Abajo of Cuba. Each year, 80% of Don Alejandro's tobacco harvest was deemed fit for use as wrapper leaf for Cuban cigars (compared to only around 35% for other plantations). In 1997, Habanos SA honored him by launching a new line of cigars bearing the name of his famous farmland. Vegas Robaina cigars, made in Havana at the former H. Upmann Factory, have quickly become popular among cigar aficionados. Don Alejandro has, himself, become a celebrity in the world of Cuban cigars, with many aficionados and tourists in Cuba flocking to his farm in the San Luis region of the Vuelta Abajo to meet the man himself and see his tobacco vegas. Don Alejandro died on April 17, 2010 after being diagnosed with cancer in 2009."
            },
            {
                "VEGUEROS", @"Vegueros is the name of a brand of premium cigars produced on the island of Cuba for Habanos SA. In 1961, the Francisco Donatién Factory in the Pinar del Río Province of Cuba began producing cigars for domestic consumption, in addition to the cigarettes it had been producing for years. These cigars were commonly rolled for national banquets and other public affairs and became colloquially known as Vegueros, after the farmers and field hands that work on Cuba's tobacco and sugar cane plantations. The first people outside of Cuba to become acquainted with these cigars were tourists on sight-seeing trips through Cuba's cigar tobacco-growing regions. In 1997, Habanos SA launched the cigars for export."
            },

        };

        public static readonly Dictionary<string, string> BrandPictures = new Dictionary<string, string>
            {
                { "QUAI-DORSAY", "https://upload.wikimedia.org/wikipedia/en/a/ac/Qd_logo.jpg" },
                { "TRINIDAD", "https://upload.wikimedia.org/wikipedia/en/3/37/Trinidad_cigars_logo.png" },
                { "SAN-CRISTOBAL", "https://upload.wikimedia.org/wikipedia/en/6/6d/Sancristoballogo.jpg" },
                { "ROMEO-Y-JULIETA", "https://upload.wikimedia.org/wikipedia/en/4/42/Rj_logo.png" },
                { "RAMON", "https://upload.wikimedia.org/wikipedia/en/5/55/Ramon_Allones.jpg" },
                { "DAVIDOFF", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Logo_Davidoff.svg/1280px-Logo_Davidoff.svg.png" },
                { "QUINTERO-BREVAS", "https://upload.wikimedia.org/wikipedia/en/d/dd/Quintero_cigars_logo.png" },
                { "BOLIVAR", "https://upload.wikimedia.org/wikipedia/en/3/3f/Bolivar_Logo.jpg" },
                { "COHIBA", "https://upload.wikimedia.org/wikipedia/en/d/de/Cohiba_cigar_logo.png" },
                { "DIPLOMATICOS", "https://upload.wikimedia.org/wikipedia/en/c/cf/Diplomaticos_logo.jpg" },
                { "EL-REY-DEL-MUNDO", "https://upload.wikimedia.org/wikipedia/en/4/4f/El-Rey-Del-Mundo.jpg" },
                { "FONSECA", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Fonseca-band.jpg/1280px-Fonseca-band.jpg" },
                { "HOYO-DE-MONTERREY", "https://upload.wikimedia.org/wikipedia/en/6/65/Hoyo_de_Monterrey.jpg" },
                { "H.UPMANN", "https://upload.wikimedia.org/wikipedia/en/d/da/H_upmann_cigars_logo.png" },
                { "JOSE-L.-PIEDRA", "https://www.cubancigarwebsite.com/img/brandlogos/jose-l-piedra-jpg" },
                { "MONTECRISTO", "https://upload.wikimedia.org/wikipedia/en/3/32/Montecristo_cigar_logo.png" },
                { "PARTAGAS", "https://sauttercigars.com/wp-content/uploads/2016/01/partagas-rs.jpg" },
                { "PUNCH", "https://upload.wikimedia.org/wikipedia/en/3/30/Punch_cigar.jpg" },
                { "VEGAS-ROBAINA", "https://upload.wikimedia.org/wikipedia/en/e/e8/Vegas-Robaina.jpg" },
                { "VEGUEROS", "https://upload.wikimedia.org/wikipedia/en/a/a6/Vegueros.jpg" },
                { "CUABA", "https://upload.wikimedia.org/wikipedia/en/3/39/Cuabalogo.JPG" },
                { "JUAN-LOPEZ", "https://www.cigar-wiki.com/images/0/02/Juanlopez_logo.jpg" },
            };

        public static readonly Dictionary<string, string> TastePictures = new Dictionary<string, string>
            {
                { "Leathery", "https://www.finestcubancigars.com/media//catalog/category/menu_taste_leathery.png" },
                { "Fruity", "https://www.finestcubancigars.com/media//catalog/category/menu_taste_fruity.png" },
                { "Vegetal", "https://www.finestcubancigars.com/media//catalog/category/menu_taste_vegetal.png" },
                { "Woody", "https://www.finestcubancigars.com/media//catalog/category/menu_taste_woody.png" },
                { "Spicy", "https://www.finestcubancigars.com/media//catalog/category/menu_taste_spicy.png" },
                { "Earthy", "https://www.finestcubancigars.com/media//catalog/category/menu_taste_earthy.png" },
            };
    }
}
